name: "🐞 Bug Report"
description: File A Bug Report
title: "[Bug]: "
labels: ["bug", "triage"]

assignees:
  - RampantLions

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: |
        How can we get in touch with you if we need more info?

        *❓Tip: If blank, we will contact you via GitHub comments.*
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: Operating System / Environment
      description: 🖥️ Choose the environment where the problem occurs, not where you develop.
      options:
        - Windows
        - macOS
        - Linux
        - Docker
        - Cloud / Server (e.g., AWS, GCP)
        - Other (please specify in Additional Context)
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: |
        What is the python version?

        *🐍 **Tip:**Run `python --version` in the same environment as the issue.*
    validations:
      required: true

  - type: textarea
    id: code-versions
    attributes:
      label: Version Info
      description: 📦 What version(s) of this code are involved?
      render: shell
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: ⚠️ How severe is the bug? Select the highest severity that accurately reflects the impact.
      options:
        - Crash / Data Loss
        - Major Functionality Broken
        - Minor Issue / Cosmetic
        - Enhancement Suggestion
    validations:
      required: true

  - type: checkboxes
    id: regression
    attributes:
      label: Regression?
      description: |
        Was this working in a previous version?

        *♻️ **Tip:**A regression means it worked before and now it’s broken.*
      options:
        - label: Yes, this is a regression (it used to work before)
        - label: No, this never worked

  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: |
        A concise description of what you're experiencing.

        *📝 **Tip:** Focus on what is happening, not why you think it's happening.*
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: |
        A concise description of what you expected to happen.

        *🌟**Tip:** Describe what success would have looked like.*
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps To Reproduce
      description: |
        Steps to reproduce the behavior.
        You can **attach code snippets or minimal files** by dragging and dropping here.
        Need help formatting your reproduction steps? Check out [this guide](https://stackoverflow.com/help/minimal-reproducible-example).
      placeholder: |
        1. In this environment...
        1. With this config...
        1. Run '...'
        1. See error...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.

        *📎 **Tip:** You can attach images or log files by clicking this area and dragging files.*
      render: shell
    validations:
      required: false

  - type: textarea
    id: config-file
    attributes:
      label: Config File
      description: |
        What is in your `pyproject.toml` file?

        *🛠️ **Tip:** If your config is large, include only the relevant parts.*
      value: "# N/A"
      render: TOML
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Add any other context about the problem here.
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        *🔗 **Tip:** Add links to similar issues, documentation, or example projects if available.*
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: ✅ By submitting this issue, you agree to the following
      options:
        - label: I agree to follow this project's [Code of Conduct](https://example.com).
          required: true
        - label: I affirm this issue is not a duplicate of an existing issue
          required: true
