blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/RampantLions/coder_plugin/discussions
    about: If you have a general question, please open a GitHub Discussion instead of an issue.
