# .github/workflows/publish-package.yml

name: Upload Python Package

on:
  push:
    tags:
      - 'v*'  # Trigger only when pushing tags like v1.0.0, v2.1.3, etc.

jobs:
  publish-package:
    runs-on: ubuntu-latest
    environment: pypi-publish

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for versioning tools or dynamic builds

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PDM and uv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pdm uv

      - name: Sync environment with uv
        run: |
          uv sync

      - name: Build Project
        run: |
          pdm build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install twine
          twine upload dist/*
